import pandas as pd
import re

# Cargar los archivos
df_wos = pd.read_excel('C:\\Users\\CYBERWORD\\Downloads\\data\\universidadespublicasprivadasfinalesl.xlsx')
#df_wos['affiliation_modified'] = df_wos['affiliation'].str.upper()

# Función para verificar si un texto contiene ciertas palabras

def contains_words(substring, text, delimiter=','):
    text = str(text)  # Convertir el valor a cadena de texto
    for part in text.split(delimiter):
        # Verificar si la "parte" comienza con la subcadena
        if part.strip().lower().startswith(substring.lower()):
            return True
    return False
# Palabras clave para buscar
words_to_searchfinal = [


('UNIV POLITECN SALECIANA','ECUADOR'),
('UNIV POLITECN SALESIAN','ECUADOR'),
('UNIV POLITECN SALESIAN UPS','ECUADOR'),
('UNIV POLITECN SALESIANA UPS','ECUADOR'),
('UNIV POLITECN SALESINA','ECUADOR'),
('UNIV POILITECN SALESIANA','ECUADOR'),
('UNIV POLITECN SALESIANA UPS','ECUADOR'),
('UNIV CATOLICA CUENCA','ECUADOR'),
('UNIV CATAL CUENCA','ECUADOR'),
('UNIVERSIDAD DEL AZUAY','ECUADOR'),
('UNIV CATOLICA CUENCA UCACUE','ECUADOR'),
('CUENCA CATHOLIC UNIV','ECUADOR'),

('UNIV PAN CUENCA','ECUADOR'),

('UNIV INTE','ECUADOR','ECUADOR'),
('MACHALA TECH UNIV','ECUADOR'),
('UNIV TECN MACHALA','ECUADOR'),
('TECH UNIV MACHALA','ECUADOR'),

('TECHNOL UNIV SAN ANTONIO MACHALA','ECUADOR'),
('UNIV METROPOLITANA','ECUADOR'), #ESTO NO VALE
('UMET UNIV METROPOLITANA ECUADOR','ECUADOR'),
('UNIV METROPOLITANA ECUADOR','ECUADOR'),
('PONTIFICIA UNIVERSIDAD CATOLICA DEL ECUADOR','ECUADOR'),
('PONTIFICIA UNIV CATOLICA ECUADOR','ECUADOR'),
('PONTIFICIA UNIV ECUADOR','ECUADOR'),
('PONTIFICIA UNIV CATOLIC ECUADOR','ECUADOR'),
('UNIV PONTIFICIA CATOLICA ECUADOR','ECUADOR'),
('PONTIFICIA UNIV CATAL ECUADOR','ECUADOR'),
('PONTIFICIA UNIV CATEL ECUADOR','ECUADOR'),
('PONTIFICIA UNIV CATHOLICA ECUADOR','ECUADOR'),
('PONTIFICIA UNIV CATILICA ECUADOR','ECUADOR'),
('PONTIFICIA UNIV ECUADOR PUCE','ECUADOR'),
('PONTIFICAL CATHOLIC UNIV ECUADOR','ECUADOR'),
('PONTIFICIA UNIV CATOL ECUADOR','ECUADOR'),
('UNIV AUTONOMA LOS ANDES AMBATO','ECUADOR'),
('UNIV TECNOL INDOAMER MATRIZ AMBATO','ECUADOR'),
('UNIV TECNOL INDOAMER AMBATO','ECUADOR'),
('UNIV TECNOL INDOAMER','ECUADOR'),
('UNIV AMER','ECUADOR'),
('UNIVERSIDAD POLITECNICA SALESIANA','ECUADOR'),
('PONTIFICIA UNIVERS CATOL ECUADOR','ECUADOR'),
('PONTIFICIA UNIVERS CATOLICA ECUADOR','ECUADOR'),
('UNIV PONTIFICIA UNIV CATOLICA ECUADOR','ECUADOR'),
('UNIV OTAVALO ECUADOR','ECUADOR'),
('UNIV OTAVALO IMBABURA','ECUADOR'),
('UNIV OTAVALO','ECUADOR'),
('CASA GRANDE UNIV','ECUADOR'),
('UNIV CASA GRANDE GUAYAQUIL','ECUADOR'),
('CASA GRANDE UNIV','ECUADOR'),
('UNIV CASA GRANDE UCG','ECUADOR'),
('UNIV RIO','ECUADOR'),

('UNIV SANTA MARIA','ECUADOR'),
('ESPIRITU SANTO','ECUADOR'),
('CATHOLIC UNIV SANTIAGO GUAYAQUIL','ECUADOR'),
('UNIV CATOLICA SANTIAGO DE GUAYAQUIL','ECUADOR'),
('SANTIAGO GUAYAQUIL CATHOLIC UNIV','ECUADOR'),
('UNIV CATOLICA SANTIAGO GUAYAQUIL UCSG','ECUADOR'),
('UNIV CATOLICA SANTIAGO GUAYAQUIL','ECUADOR'),
('UNIV CATOL SANTIAGO GUAYAQUIL','ECUADOR'),
('CATHOL UNIV GUAYAQUIL','ECUADOR'),
('GUAYAQUIL CATHOLIC UNIV','ECUADOR'),
('SANTIAGO GUAYAQUIL CATHOLIC UNIV UCSG','ECUADOR'),
('UNIV CATAL SANTIAGO GUAYAQUIL','ECUADOR'),
('UNIV CATHOLIC SANTIAGO GUAYAQUIL','ECUADOR'),
('UNIV CATOLIC SANTIAGO GUAYAQUIL','ECUADOR'),
('SANTIAGO UNIV','ECUADOR'),
('UNIV CATOLICA DE SANTIAGO GUAYAQUIL','ECUADOR'),
('UNIV CATOLICA MICA SANTIAGO GUAYAQUIL','ECUADOR'),
('UNIV CATOLICA SANTIAGO GUAYAQUI','ECUADOR'),
('UNIV SAN FRANCISCO QUITO','ECUADOR'),
('UNIV SAN FRANCISCO QUITO USFQ','ECUADOR'),
('UNIV SAN FRANCISCO DE QUITO','ECUADOR'),
('SAN FRANCISCO QUITO UNIV','ECUADOR'),
('SAN FRANCISCO UNIV QUITO','ECUADOR'),
('SAN FRANCISCO QUITO UNIV USFQ','ECUADOR'),
('UNIV SAN FRANSCISCO QUITO','ECUADOR'),
('UNIV SAN FRANCISCO QUITO ECUADOR','ECUADOR'),
('UNIV SAN FRANCISCO DE QUITO USFQ','ECUADOR'),
('UNIV SAN FRANCISCO DE QUITO USFQ','ECUADOR'),	
('UNIV SAN FRANCISCO USFQ','ECUADOR'),
('UNIV SAN FRANSISCO QUITO','ECUADOR'),
('UNIV SAN FRANCISCO','ECUADOR'),
('UNIVERS SAN FRANCISCO QUITO','ECUADOR'),
('UNIVERS SAN FRANCISCO QUITO USFQ','ECUADOR'),
('SAN FRANCISCO DE QUITO UNIV','ECUADOR'),
('SAN FRANCISCO DE QUITO UNIV USFQ','ECUADOR'),
('SAN FRANCISCO DEQUITO UNIV','ECUADOR'),
('UNIV SUN FRANCISCO QUITO','ECUADOR'),
('UNWERSIDAD SAN FRANCISCO QUITO','ECUADOR'),
('UNIV LAICA VICENTE ROCAFUERTE GUAYAQUIL ULVR','ECUADOR'),
('UNIV VICENTE ROCAFUERTE GUAYAQUIL','ECUADOR'),
('UNIV LAICA VICENTE ROCAFUERTE','ECUADOR'),
('UNIV LAICA VICENTE ROCAFUERTE GUAYAQUIL','ECUADOR'),
('UNIV LAICA VICENTE ROCAFUERTE GUAYAQUIL ULVR','ECUADOR'),
('UNIV VICENTE ROCAFUERTE GUAYAQUIL','ECUADOR'),
('UNIVERSIDAD DE ESPECIALIDADES ESPIRITU SANTO','ECUADOR'),
('UNIV ESPECIALIDADES ESPIRITU SANTO','ECUADOR'),
('UNIV ESPIRITU SANTO ECUADOR','ECUADOR'),
('UNIV ESPECIALIDADES ESPIRITU SANTO UEES','ECUADOR'),
('ESPIRITU SANTO UNIV UEES','ECUADOR'),
('ESPECIALIDADES ESPIRITU SANTO UNIV','ECUADOR'),
('UNIV ESPIRITU SANTO GUAYAQUIL','ECUADOR'),
('UNIV ESPIRITU SANTO SAMBORONDON','ECUADOR'),
('UNIV ESPECIALIDADES ESPIRITU SANTO ECUADOR','ECUADOR'),
('UNIV ESPECIALIDADES ESPIRITU SANTO GUAYAQUIL','ECUADOR'),
('UNIV ESPECIAL ESPIRITU SANTO','ECUADOR'),
('UNIV ESPECIAL ESPIRITU SANTO ECUADOR','ECUADOR'),
('UNIV ESPECIALIDADES ESPIRITU SANTO AV','ECUADOR'),
('UNIV ESPECIALIDADES ESPIRITU SANTO GUAYAQUIL ECUA','ECUADOR'),
('UNIV ESPECIALIDADES ESPITIRU SANTO','ECUADOR'),
('UNIV ESPECIALIDADES ESPRITU SANTO','ECUADOR'),
('UNIV SPIRITU SANTO ECUADOR','ECUADOR'),
('UNIV ESPIRITU SANTO','ECUADOR'),
('UNIV ESPIRITU SANTO ECUADOR TOSCANA','ECUADOR'),
('UNIV ESPIRITU SANTOECUADOR','ECUADOR'),
('UNIV ESPIRTIU SANTO','ECUADOR'),
('UNIVERS ESPIRITU SANTO','ECUADOR'),
('UNIANDES AMBATO','ECUADOR'),
('UNIANDES BABAHOYO','ECUADOR'),
('UNIANDES ECUADOR','ECUADOR'),
('UNIANDES TULCAN	','ECUADOR'),
('UNIV REG AMAZONICA','ECUADOR'),
('UNIV REG AMAZONICA','ECUADOR'),
('UNIV REG AUTONOMA ANDES EXTENS QUEVEDO','ECUADOR'),
('UNIV REG AUTONOMA ANDES EXTENS RIOBAMBA','ECUADOR'),
('INDOAMER TECHNOL UNIV AMBATO','ECUADOR'),
('IESE BUSINESS SCHOOL','ECUADOR'),
('UNIV ECOTEC ECUADOR','ECUADOR'),
('UNIV ECOTEC GUAYAQUIL','ECUADOR'),
('UNIV ECOTEC','ECUADOR'),
('UNIV TECNOL EMPRESARIAL GUAYAQUIL','ECUADOR'),
('UNIV TECNOL EMPRESARIAL','ECUADOR'),
('UNIV TECNOL EMPRESARIAL GUAYAQUIL UTEG','ECUADOR'),
('LOS HEMISFERIOS UNIV','ECUADOR'),
('UNIV HEMISFERIOS ECUADOR','ECUADOR'),
('UNIV HEMISFERIOS QUITO','ECUADOR'),
('UNIV HEMISFERIOS','ECUADOR'),
('UNIV LOS HEMISFERIOS','ECUADOR'),
('LOS HEMISFERIOS UNIV','ECUADOR'),
('UNIV IBEROAMERICANA ECUADOR','ECUADOR'),
('PARTICULAR SYST UNIV LOJA','ECUADOR'),
('PARTICULAR TECH UNIV LOJA','ECUADOR'),
('PROMETEO SENESCYT PARTICULAR TECH UNIV LOJA','ECUADOR'),
('TECN PARTICULAR UNIV LOJA','ECUADOR'),
('UNIV TACN PARTICULAR LOJA','ECUADOR'),
('UNIV TCN PARTICULAR LOJA','ECUADOR'),
('UNIV TCNICA PARTICULAR LOJA','ECUADOR'),
('UNIV TECN PARICULAR LOJA','ECUADOR'),
('UNIV TECN PARTICULAR LA LOJA','ECUADOR'),
('UNIV TECN PARTICULAR LOJ','ECUADOR'),
('UNIV TECN PARTICULAR LOJ ECUADOR','ECUADOR'),
('UNIV TEN PARTICULAR LOJA','ECUADOR'),
('UNIV TECN PARTICULAS LOJA','ECUADOR'),
('UNIV TEN PARTICULAR LOJA','ECUADOR'),
('UNIV TECN PARTICULAR LOJA UTPL','ECUADOR'),
('UNIVERSIDAD TECNICA PARTICULAR DE LOJA','ECUADOR'),
('UNIVERS TECN PARTICULAR LOJA','ECUADOR'),
('UNIV TOCN PARTICULAR LOJA','ECUADOR'),
('SAN GREGORIO PORTOVIEJO UNIV','ECUADOR'),
('UNIV SAN GREGORIO PORTOVIEJO','ECUADOR'),
('UNIV SAN GREGORIO DE PORTOVIEJO','ECUADOR'),
('UNIV SAN GREGORIO ECUADOR','ECUADOR'),
('UNIV SAN GREGORIO PORTOVIEJO MANABI ECUADOR','ECUADOR'),
('PRIVATE TECHNOL UNIV LOJA','ECUADOR'),
('TECN PARTICULAR LOJA UNIV','ECUADOR'),
('UEES UNIV GUAYAQUIL','ECUADOR'),
('HOLY SPIRIT UNIV','ECUADOR'),
('HOLY SPIRIT UNIV GUAYAQUIL ECUADOR','ECUADOR'),
('HOLY SPIRIT UNIV SPECIALTIES','ECUADOR'),
('UNIV PARTICULAR SAN GREGORIO PORTOVIEJO','ECUADOR'),
('UNIV ALFREDO PEREZ GUERRERO','ECUADOR'),
('UNIV ESPECIALIDADES TURIST UDET','ECUADOR'),
('UNIV ESPECIALIDADES TURISTICAS','ECUADOR'),
('UNIV TECNOL INDOAMERICA','ECUADOR'),
('UNIV INT SEK','ECUADOR'),
('UNIV TECNOL EQUINOCCIAL','ECUADOR'),
('UNIV TECNOL EQUINOCCIAL UTE','ECUADOR')
,('UNIV TECN EQUINOCCIAL','ECUADOR'),
('UNIV TECNOLOG EQUINOCCIAL','ECUADOR'),('EQUINOCCIAL TECH UNIV','ECUADOR'),
('EQUINOCCIAL TECHNOL UNIV','ECUADOR'),
('EQUINOCTIAL TECHNOL UNIV ECUADOR','ECUADOR'),
('UNIV TECNOL EQUICCNOCIAL','ECUADOR'),
('UNIV TECNOL EQUINOCCIAIL','ECUADOR'),
('UNIV ISRAEL','ECUADOR'),
('UNIV IAS AMERICAS','ECUADOR'),
('UNIV IAS AMERICAS UDLA','ECUADOR'),
('UNIV LAS AMER EQUADOR','ECUADOR'),
('UNIV LAS AMER','ECUADOR'),
('UNIV LAS AMER QUITO ECUADOR','ECUADOR'),
('UNIV LAS AMER UDLA ECUADOR','ECUADOR'),
('UNIV LAS AMER UDLA QUITO ECUADOR','ECUADOR'),
('UNIV LAS AMERICAS UDLA','ECUADOR'),
('UNIVERSIDAD DE LAS AMERICAS ECUADOR','ECUADOR'),
('ESPAE ESCUELA NEGOCIOS ESPOL','ECUADOR'),
('FLASCO','ECUADOR'),
('UNIV REG AUTONOMA ANDES','ECUADOR'),
('UNIV REG AUTONOMA ANDES UNIANDES','ECUADOR'),
('UNIV REG AUTONOMA LOS ANDES UNIANDES','ECUADOR'),
('UNIV AUTONOMA LOS ANDES','ECUADOR'),
('UNIV AUTONOMA REG LOS ANDES','ECUADOR'),
('UNIV AUTONOMA REG ANDES UNIANDES','ECUADOR'),
('UNIV REG AUTONOMA ANDES EXTENS','ECUADOR'),
('UNIV AUTONOMA REG ANDES','ECUADOR'),
('UNIV REG AUTONOMA ANDES UNIANDES','ECUADOR'),
('UNIV REG AUTONOMA LOS ANDES','ECUADOR'),
('REG AUTONOMA LOS ANDES UNIANDES','ECUADOR'),	
('UNIANDES UNIV REG AUTONOMA ANDES','ECUADOR'),
('UNIV REG AUTONOMA ANDES ECUADOR','ECUADOR'),
('UNIV REG AUTONOMA ANDES LOS ANDES','ECUADOR'),
('UNIV REG AUTONOMA ANDES LOS ECUADOR','ECUADOR'),
('UNIV REG AUTONOMA ANDES UNIANDES','ECUADOR'),
('UNIV REG AUTONOMA IOS ANDES UNIANDES','ECUADOR'),
('UNIV REG AUTONOMA LOS ANDES ECUADOR','ECUADOR'),
('UNIV REG AUTONOMA LOS ANDES EXTENS','ECUADOR'),
('UNIV REG AUTONOMA LOS ANDES UNIAND','ECUADOR'),
('UNIV REG AUTONOMA LOS ANDES UNIANDES','ECUADOR'),
('UNIV INT ECUADOR','ECUADOR')


    
]

# Identificar las filas que contienen las palabras clave en la columna 'affiliation'
mask_affiliation = pd.Series([False] * len(df_wos))
for word_pair in words_to_searchfinal:
    mask_affiliation |= df_wos['affiliation'].apply(lambda x: contains_words(word_pair[0], x) and contains_words(word_pair[1], x))

# Identificar las filas que contienen las palabras clave en la columna 'affiliations'
mask_affiliations = pd.Series([False] * len(df_wos))
for word_pair in words_to_searchfinal:
    mask_affiliations |= df_wos['affiliations'].apply(lambda x: contains_words(word_pair[0], x, delimiter=';') and contains_words(word_pair[1], x, delimiter=';'))

# Combinar las máscaras
mask_total = mask_affiliation | mask_affiliations

# Filtrar las filas que contienen las palabras clave
df_containstotalprivadas = df_wos[mask_total]
df_containstotalprivadas.to_excel('universidadesprivadasfinales.xlsx', index=False)
# Reemplazos para realizar en las filas filtradas
replacements = {
    'UNIVERSIDAD ESTATAL DE MILAGRO':'UNIVERSIDAD ESTATAL DE MILAGRO',
    'UNIV ESTATAL MILAGROS': 'UNIVERSIDAD ESTATAL DE MILAGRO',
    'UNIV ESTATAL MILAGRO': 'UNIVERSIDAD ESTATAL DE MILAGRO',
    'STATE UNIV MILAGRO': 'UNIVERSIDAD ESTATAL DE MILAGRO',
    'UNIV ESTALAL MILAGRO UNEMI': 'UNIVERSIDAD ESTATAL DE MILAGRO',
    # ... puedes agregar más reemplazos aquí ...
}

# Aplicar los reemplazos
#df_containstotal['affiliation_modified'] = df_containstotal['affiliation_modified'].replace(replacements, regex=True)

# Eliminar filas duplicadas
#df_containstotal = df_containstotal.drop_duplicates()
#df_containstotalfinal=df_containstotal
# Guardar el resultado

